import { Sora } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Header from "./components/Header";
import PageAnimatePresence from "./components/PageAnimatePresence";
import Favicon from "../public/favicon.ico";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "태영이 포트폴리오",
  description: "Generated by 태영",
  icons: {
    icon: [{ rel: "icon", url: Favicon.src }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`page bg-mainbg text-white ${sora.variable} font-sora relative`}
      >
        <Nav />
        <Header />
        <PageAnimatePresence>{children}</PageAnimatePresence>
      </body>
    </html>
  );
}
